Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,13 +18,20 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           python -m pip install feedparser requests beautifulsoup4 html2text selenium==4.9.0
-          python -m pip show selenium  # Проверяем, установлен ли selenium
-          python -m pip list  # Выводим список всех установленных пакетов
+          python -m pip show selenium
+          python -m pip list
           sudo apt-get update
           sudo apt-get install -y chromium chromium-chromedriver
-          # Удаляем старую ссылку, если она существует, и создаем новую
+          # Проверяем, что находится в /usr/bin/chromedriver
+          ls -l /usr/bin/chromedriver || echo "chromedriver not found in /usr/bin"
+          # Удаляем старую ссылку или файл
           sudo rm -f /usr/bin/chromedriver
+          # Проверяем, что файл удален
+          ls -l /usr/bin/chromedriver || echo "chromedriver removed from /usr/bin"
+          # Создаем новую ссылку
           sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
+          # Проверяем, что ссылка создана
+          ls -l /usr/bin/chromedriver
       - name: Run script
         run: python rss_parser.py
       - name: Commit changes
